import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BasicTemplate } from "@/components/templates/BasicTemplate";

const inter = Inter({ subsets: ["latin"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <BasicTemplate>{children}</BasicTemplate>;
}
