apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-sns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chaos-sns
  template:
    metadata:
      labels:
        app: chaos-sns
    spec:
      containers:
      - name: backend-node
        image: backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
      - name: frontend-node
        image: frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          protocol: TCP
      - name: database-node
        image: database:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          protocol: TCP
